# Generated by Django 4.1.7 on 2023-04-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default_value', max_length=10000)),
                ('time', models.CharField(default='default_value', max_length=10000)),
                ('detail', models.CharField(default='default_value', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='default_value', max_length=10000)),
                ('value', models.CharField(default='default_value', max_length=20)),
            ],
        ),
    ]
